name: Elixir CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  ELIXIR_VERSION: 1.13
  OTP_VERSION: 24.2
  MIX_ENV: test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          elixir-version: "${{ env.ELIXIR_VERSION }}"
      - name: Install mix dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run tests
        run: mix do compile --warnings-as-errors, test
      - name: Run credo
        run: mix do compile --warnings-as-errors, credo --strict
